/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f411xe.h"
#include "motor_control.h"
#include "uart.h"
#include "protocol.h"
#include "timer.h"
#include "i2c.h"
#include "vl53l0x_api.h"

/* Configuration */

// Default driving speed when no speed is specified (in percentage)
#define DEFAULT_SPEED 70U

// Watchdog timeout : motors stop if no command received (in ms)
#define WATCHDOG_MS 500U

// Protocol frame size : 1 direction byte + 2 speed digits
#define FRAME_SIZE 3U

uint32_t SystemCoreClock = 16000000U;

// Flag to stop forward movement if an obstacle is here
volatile uint8_t obstacle_front = 0U;

/**
 * Watchdog
 *
 * Stops the motors if no valid command has been received
 * within WATCHDOG_MS milliseconds.
 */
static void watchdog_check(uint32_t last_cmd_tick)
{
    if ((timer_GetTick() - last_cmd_tick) >= WATCHDOG_MS)
    {
        motor_Stop();
    }
}

int main(void)
{
    /* Initialize peripherals */
    timer_Init();
    motor_Init();
    UART_Init();

    I2C_Init();

    tof_init_protocol();  // Full VL53L0X init + diagnostic

    /* Safe initial state */
    motor_Stop();

    /* HC-05 startup delay  */
    timer_DelayMs(300U);

    UART_SendString("CAR READY\r\n");
    UART_SendString("Protocol: DIR(F/B/L/R/S) + SPEED(00-99)\r\n");
    UART_SendString("Example : F75 = Forward 75%\r\n");

    uint32_t last_cmd_tick = timer_GetTick();

    while (1)
    {
        /* Read distance sensor */
        check_obstacle();

        /* Process pending bytes from RX buffer */
        protocol_ProcessRx(&last_cmd_tick);

        /* Watchdog */
        watchdog_check(last_cmd_tick);
    }
}
